### ISSUE TITLE
Swift run on 10.12 Sierra

### ISSUE THREAD

**Issue by JamesFrank2525** [Dev1an/Atem-Simulator#1]
Hi, I am trying to run the software, but when I type the command "swift run", I get 

error: terminated(1): /Library/Developer/CommandLineTools/usr/bin/swift-build-tool -f /Users/kubaszczygielski/Downloads/Atem-Simulator-master/commandLineApp/.build/debug.yaml commandLineApp.exe

I use macOS 10.12 Sierra. Is it necessary for me to update to 10.13?

**Comment by Dev1an** [comment]
which swift toolchain are you using?

**Comment by JamesFrank2525** [comment]
4.2.1. The thing is, in XCode it shows that Swift is 4.2.1, but the system itself only perceives Package Manager as 4.0.0.

**Comment by Dev1an** [comment]
I'm not sure if it would work with the swift package manager (`>swift run`, `swift build` etc.), but with Xcode it's possible to create macOS 10.12 executables: See [release 0.2.1](https://github.com/Dev1an/Atem-Simulator/releases/tag/0.2.1)

**Comment by JamesFrank2525** [comment]
Ok, now the app runs, thank you! But Atem Software still doesn’t recognize it. Should I set any specific IP in the software?

**Comment by Dev1an** [comment]
Great! Yes you should set the IP address to localhost (127.0.0.1). May I ask which version of the ATEM software you are using?

**Comment by JamesFrank2525** [comment]
Ok, now it tells me that I should update my switcher. This is probably because I am using software version 7.3, but it is the last one compatible with my Atem 1M/E Production Switcher, so I think I will just connect my switcher (wanted to mess around with the software while I’m somewhere just with my laptop but I can live with that). It would be great in the future to see any „bigger” switcher simulated in order to navigate around all functions (like 2M/E). Anyway, great job. Thank you and keep up the good work!

**Comment by Dev1an** [comment]
You can use [release 0.1.1](https://github.com/Dev1an/Atem-Simulator/tree/0.1.1) together with the ATEM software 7.3. I tested this setup before. The only thing you wil need to do is to rebuild that version for macOS 10.12, because I built that version for macOS 10.13 at that time.

So basically open the old project ([0.1.1](https://github.com/Dev1an/Atem-Simulator/tree/0.1.1)) and change the deployment target like I did in 1078a4a and you will be able to simulate a 1M/E switcher

**Comment by JamesFrank2525** [comment]
Yeah, if only I could open the project - last version of Xcode that Sierra supports is 9.2, so I cannot edit it.

**Comment by Dev1an** [comment]
Ah yes of course, let me build this for you.
[AtemSimulator 0.1.2 for macOS X.12](https://github.com/Dev1an/Atem-Simulator/files/2697796/AtemSimulator.0.1.2.macOS.X.12.zip)
